## Import Libraries

In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error , r2_score

## Understand & Cleanup Data

In [32]:
d = pd.read_csv("Student_Performance.csv")
d

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [33]:
d.duplicated().sum()

np.int64(127)

In [34]:
d.isna().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [35]:
d.drop_duplicates(inplace=True)
d.duplicated().sum()

np.int64(0)

In [36]:
d.info()

<class 'pandas.DataFrame'>
Index: 9873 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     9873 non-null   int64
 1   Previous Scores                   9873 non-null   int64
 2   Extracurricular Activities        9873 non-null   str
 3   Sleep Hours                       9873 non-null   int64
 4   Sample Question Papers Practiced  9873 non-null   int64
 5   Performance Index                 9873 non-null   float64
dtypes: float64(1), int64(4), str(1)
memory usage: 539.9 KB

In [37]:
le= LabelEncoder()
d["Extracurricular Activities"]=le.fit_transform(d["Extracurricular Activities"])
d

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [38]:
x = d.iloc[: , :5]
y= d.iloc[:, 5:]

In [39]:
x

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2
3,5,52,1,5,2
4,7,75,0,8,5
...,...,...,...,...,...
9995,1,49,1,4,2
9996,7,64,1,8,5
9997,6,83,1,8,5
9998,9,97,1,7,0
9999,7,74,0,8,1

In [40]:
y

      Performance Index
0                  91.0
1                  65.0
2                  45.0
3                  36.0
4                  66.0
...                 ...
9995               23.0
9996               58.0
9997               74.0
9998               95.0
9999               64.0

[9873 rows x 1 columns]

## Train

In [41]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2, random_state = 42)

In [42]:
lr = LinearRegression()
lr.fit(x_train , y_train)
pred = lr.predict(x_test)

In [43]:
print(y_test , pred)

      Performance Index
6099               47.0
106                76.0
9265               62.0
4707               23.0
2155               76.0
...                 ...
8732               19.0
3112               39.0
5297               77.0
6116               88.0
5088               34.0

[1975 rows x 1 columns] [[46.48001281]
 [80.2853795 ]
 [61.06518835]
 ...
 [77.08443628]
 [86.24676576]
 [35.8793377 ]]

In [44]:
print("Mean squared error: ", mean_squared_error(y_test, pred))
print("R2 Score: ",r2_score(y_test, pred))

Mean squared error:  4.305900938538479
R2 Score:  0.9884301209927054