### Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder , OrdinalEncoder
from sklearn.model_selection import train_test_split

### Data

In [2]:
d = pd.read_csv('animals_Hometask (2).csv')
d.head(3)

   AnimalID     Species   Size  Legs CanFly  Color  Weight DangerLevel
0         1  Flufficorn  Small     4     No   Pink     3.0         Low
1         2   Sparkworm   Tiny     0    Yes   Blue     0.5      Medium
2         3    Gigacorn  Large     4     No  White   120.0        High

In [3]:
print(d.isna().sum())
print("\n Duplicated: ", d.duplicated().sum())

AnimalID       0
Species        0
Size           2
Legs           0
CanFly         2
Color          1
Weight         0
DangerLevel    3
dtype: int64

 Duplicated:  0

In [4]:
d.dropna(inplace=True)
d.isna().sum()

AnimalID       0
Species        0
Size           0
Legs           0
CanFly         0
Color          0
Weight         0
DangerLevel    0
dtype: int64

In [5]:
d.head(3)

   AnimalID     Species   Size  Legs CanFly  Color  Weight DangerLevel
0         1  Flufficorn  Small     4     No   Pink     3.0         Low
1         2   Sparkworm   Tiny     0    Yes   Blue     0.5      Medium
2         3    Gigacorn  Large     4     No  White   120.0        High

### Split ==> Encode

In [6]:
x = d.drop(['Species', 'AnimalID'], axis=1)
y = d['Species']

In [7]:
x_train , x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [8]:
Or = OrdinalEncoder() # made for features
le = LabelEncoder() # made for target values

x_train = Or.fit_transform(x_train)
x_test  = Or.transform(x_test)

y_train = le.fit_transform(y_train)
y_test  = le.transform(y_test)

### Predict

In [9]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
pred = lr.predict(x_test)

/home/suupatruupa/Documents/yurrr/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

### Check

In [10]:
print("Classifciation Report: \n", classification_report(y_test, pred))
print("\n Accuracy score: ", accuracy_score(y_test , pred))

Classifciation Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         3
           3       1.00      1.00      1.00         5
           4       1.00      1.00      1.00         3
           7       1.00      1.00      1.00         2

    accuracy                           1.00        19
   macro avg       1.00      1.00      1.00        19
weighted avg       1.00      1.00      1.00        19


 Accuracy score:  1.0