In [143]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder

In [144]:
d = pd.read_csv("final_health_project.csv")
d.head()

     ID  Age  Weight  Height  Exercise_Hours Diet_Quality BMI_Category
0  7402  NaN     NaN     NaN             NaN          NaN       Normal
1  5835  NaN     NaN     NaN             NaN          NaN   Overweight
2  2123  NaN     NaN     NaN             NaN          NaN   Overweight
3  8789  NaN     NaN     NaN             NaN          NaN       Normal
4   305  NaN     NaN     NaN             NaN          NaN       Normal

In [145]:
d.shape

(10100, 7)

In [146]:
d.drop('ID',axis=1,inplace=True)

In [147]:
d.isna().sum()
d.fillna(d.mean(numeric_only=True), inplace=True)
d['Diet_Quality'] = d['Diet_Quality'].fillna(d['Diet_Quality'].mode()[0])
d.isna().sum()

Age               0
Weight            0
Height            0
Exercise_Hours    0
Diet_Quality      0
BMI_Category      0
dtype: int64

In [148]:
d.head(10)

        Age     Weight      Height  Exercise_Hours Diet_Quality BMI_Category
0  38.80178  82.727073  170.071607        5.019202         Good       Normal
1  38.80178  82.727073  170.071607        5.019202         Good   Overweight
2  38.80178  82.727073  170.071607        5.019202         Good   Overweight
3  38.80178  82.727073  170.071607        5.019202         Good       Normal
4  38.80178  82.727073  170.071607        5.019202         Good       Normal
5  38.80178  82.727073  170.071607        5.019202         Good   Overweight
6  38.80178  82.727073  170.071607        5.019202         Good   Overweight
7  38.80178  82.727073  170.071607        5.019202         Good       Normal
8  38.80178  82.727073  170.071607        5.019202         Good       Normal
9  38.80178  82.727073  170.071607        5.019202         Good       Normal

In [149]:
d.duplicated().sum()
d.drop_duplicates(inplace=True)
d.duplicated().sum()

np.int64(0)

In [150]:
le = LabelEncoder()
d['Diet_Quality'] = le.fit_transform(d['Diet_Quality'])
d['BMI_Category'] = le.fit_transform(d['BMI_Category'])
d

,Age,Weight,Height,Exercise_Hours,Diet_Quality,BMI_Category
0,38.80178,82.727073,170.071607,5.019202,1,0
1,38.80178,82.727073,170.071607,5.019202,1,1
22,38.80178,82.727073,170.071607,5.019202,1,2
101,25.00000,59.000000,176.000000,1.000000,2,0
102,24.00000,83.000000,190.000000,10.000000,1,0
...,...,...,...,...,...,...
10095,56.00000,63.000000,163.000000,6.000000,0,0
10096,20.00000,67.000000,169.000000,2.000000,0,0
10097,18.00000,114.000000,169.000000,7.000000,0,0
10098,58.00000,80.000000,170.000000,4.000000,1,1
10099,21.00000,59.000000,155.000000,10.000000,1,0

In [151]:
x = d.drop('BMI_Category',axis=1)
y = d['BMI_Category']
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 42)

In [152]:
lg = LogisticRegression(max_iter=1000)
lg.fit(x_train, y_train)
pred = lg.predict(x_test)
print(accuracy_score(y_test, pred))

0.7141414141414142

In [153]:
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)
predK = knn.predict(x_test)
print(accuracy_score(y_test, pred))

0.7141414141414142